export const artists = [
    {
        id: 1,
        name: "Sauti Sol",
        genre: "Afro-Pop",
        status: "live",
        voteCount: 1240,
        scheduledTime: "10:30 PM",
        votingSecondsRemaining: 180, // 3 minutes for demo
        isVotingPaused: false,
        image: "/images/artist_01_amani_kariuki.png",
        bio: "Sauti Sol is an award-winning afro-pop group from Nairobi, Kenya. They have topped the charts across the continent with their soulful harmonies and infectious rhythms.",
        discography: [
            { title: "Midnight Train", year: 2020 },
            { title: "Afrikan Sauce", year: 2019 },
            { title: "Live and Die in Afrika", year: 2015 },
        ],
    },
    {
        id: 2,
        name: "Burna Boy",
        genre: "Afro-Fusion",
        status: "upcoming",
        voteCount: 0,
        scheduledTime: "11:15 PM",
        image: "/images/artist_02_zuri_mwangi.png",
        bio: "The African Giant. Burna Boy has revolutionized the global sound with his unique fusion of dancehall, reggae, and afrobeat.",
        discography: [
            { title: "Love, Damini", year: 2022 },
            { title: "Twice as Tall", year: 2020 },
            { title: "African Giant", year: 2019 },
        ],
    },
    {
        id: 3,
        name: "Wizkid",
        genre: "Afrobeats",
        status: "upcoming",
        voteCount: 0,
        scheduledTime: "12:00 AM",
        image: "/images/artist_03_kofi_wanjiru.png",
        bio: "Starboy. Wizkid is one of the most influential African artists of all time, known for his smooth vocals and global collaborations.",
        discography: [
            { title: "More Love, Less Ego", year: 2022 },
            { title: "Made in Lagos", year: 2020 },
            { title: "Sounds from the Other Side", year: 2017 },
        ],
    },
    {
        id: 4,
        name: "Tems",
        genre: "Alt-R&B",
        status: "closed",
        voteCount: 850,
        scheduledTime: "09:45 PM",
        image: "/images/artist_04_makena_njoroge.png",
        bio: "Tems is a Nigerian singer and songwriter whose soulful and unique vocal style has earned her international acclaim and Grammy recognition.",
        discography: [
            { title: "For Broken Ears", year: 2020 },
            { title: "If Orange Was a Place", year: 2021 },
        ],
    },
    {
        id: 5,
        name: "Diamond Platnumz",
        genre: "Bongo Flava",
        status: "closed",
        voteCount: 2100,
        scheduledTime: "09:00 PM",
        image: "/images/artist_05_jabali_odhiambo.png",
        bio: "The King of Bongo Flava. Diamond Platnumz is a Tanzanian powerhouse known for his high-energy performances and massive social media following.",
        discography: [
            { title: "First of All", year: 2022 },
            { title: "A Boy From Tandale", year: 2018 },
        ],
    },
    {
        id: 6,
        name: "Nesta",
        genre: "Reggae",
        status: "upcoming",
        voteCount: 0,
        scheduledTime: "12:45 AM",
        image: "/images/artist_06_imara_kipchoge.png",
        bio: "A rising star in the contemporary reggae scene, bringing fresh energy and conscious lyrics to the next generation of listeners.",
        discography: [{ title: "Roots & Hype", year: 2023 }],
    },
];

export const votingQuestions = [
    {
        id: "performance",
        text: "Overall performance - How much did you enjoy this performance?",
        lowLabel: "Didn't connect",
        highLabel: "Loved it!!",
    },
    {
        id: "connection",
        text: "Crowd Connection: Did the artist connect with you and the crowd during their performance?",
        lowLabel: "Not at all",
        highLabel: "I felt every moment",
    },
    {
        id: "replay",
        text: "Replay Value: Would you want to watch or listen to this artist again in your own time?",
        lowLabel: "Nope",
        highLabel: "Definitely yes",
    },
    {
        id: "rating",
        text: "Overall, how would you rate the artist based on their performance?",
        lowLabel: "Okay",
        highLabel: "Amazing!",
    },
];
